
export const REQUEST_VOTERING_BY_ID = "REQUEST_VOTERING_BY_ID";
export const RECEIVED_VOTERING_BY_ID = "RECEIVED_VOTERING_BY_ID";



export const REQUEST_LEDAMOTER = "REQUEST_LEDAMOTER";
export const RECEIVED_LEDAMOTER = "RECEIVED_LEDAMOTER";

export const SET_LEDAMOT = "SET_LEDAMOT";





export const REQUEST_NEWS = "REQUEST_NEWS";
export const RECEIVED_NEWS = "RECEIVED_NEWS";
