
export const REQUEST_VOTERING_BY_ID = "REQUEST_VOTERING_BY_ID";
export const RECEIVED_VOTERING_BY_ID = "RECEIVED_VOTERING_BY_ID";

export const REQUEST_VOTERING_BY_YEAR = "REQUEST_VOTERING_BY_YEAR";
export const RECEIVED_VOTERING_BY_YEAR = "RECEIVED_VOTERING_BY_YEAR";

export const TOGGLE_VOTERING_FETCHED = "TOGGLE_VOTERING_FETCHED"

export const REQUEST_LEDAMOTER = "REQUEST_LEDAMOTER";
export const RECEIVED_LEDAMOTER = "RECEIVED_LEDAMOTER";

export const REQUEST_LEDAMOTER_BY_PARTY = "REQUEST_LEDAMOTER_BY_PARTY";
export const RECEIVED_LEDAMOTER_BY_PARTY = "RECEIVED_LEDAMOTER_BY_PARTY";

export const SET_LEDAMOT = "SET_LEDAMOT";
export const SET_LEDAMOT_FETCHED = "SET_LEDAMOT_FETCHED";




export const REQUEST_NEWS = "REQUEST_NEWS";
export const RECEIVED_NEWS = "RECEIVED_NEWS";
